spring:
  data:
    redis:
      port: 6379
      host: localhost
      channel:
        follower: follower_channel
        achievement: achievement_channel
        recommendation-received: recommendation_received_channel
        achievement-goal: goal_achieve

  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email@gmail.com #https://www.baeldung.com/spring-email
    password: whatever
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  messages:
    basename: messages

server:
  port: 8083

logging:
  level:
    root: info

vonage: #https://dashboard.nexmo.com/getting-started/sms
  api:
    key: whatever
    secret: whatever

project-service:
    host: localhost
    port: 8082
user-service:
    host: localhost
    port: 8080

company:
  name: "CorporationX"