spring:
  data:
    redis:
      port: 6379
      host: localhost
      channel:
        follower: follower_channel
        achievement: achievement_channel

  mail:
    host: smtp.gmail.com
    port: 587
    username: vladerm2081@gmail.com
    password: qmqthhmnmsufpzdd
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  messages:
    basename: messages

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: notification-processing-group

    listener:
      ack-mode: manual

    topics:
      comment_create_topic: comment-create

server:
  port: ${SERVER_PORT:8083}

logging:
  level:
    root: info

#Можно зарегистрировать аккаунт без привязки карты. Будет 2 евро на отправку тестовых SMS
vonage: #https://dashboard.nexmo.com/getting-started/sms
  api:
    key: whatever
    secret: whatever

project-service:
    host: localhost
    port: 8082
user-service:
    host: localhost
    port: 8080
