spring:
  data:
    redis:
      host: localhost  # Хост Redis сервера
      port: 6379       # Порт Redis сервера
      connect-timeout: 5000  # Таймаут подключения в миллисекундах
      read-timeout: 3000     # Таймаут чтения в миллисекундах
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME} # Логин приложения Gmail
    password: ${EMAIL_PASSWORD} # Пароль приложения Gmail
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl.trust: smtp.gmail.com

  messages:
    basename: messages

server:
  port: 8083

logging:
  level:
    root: info

#Можно зарегистрировать аккаунт без привязки карты. Будет 2 евро на отправку тестовых SMS
vonage: #https://dashboard.nexmo.com/getting-started/sms
  api:
    key: whatever
    secret: whatever

project-service:
  host: localhost
  port: 8082
user-service:
  host: localhost
  port: 8080
