CREATE TABLE pending_notifications
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receiver_id       BIGINT      NOT NULL,
    target_entity_id  BIGINT      NOT NULL,
    related_entity_id BIGINT,
    event_type        VARCHAR(50) NOT NULL,
    status            VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    sent_at           TIMESTAMPTZ
);