CREATE TABLE pending_notifications
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receiver_id      BIGINT      NOT NULL,
    target_entity_id BIGINT      NOT NULL,
    event_data       JSONB       NOT NULL,
    event_type       VARCHAR(50) NOT NULL,
    status           VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    sent_at          TIMESTAMPTZ
);

CREATE INDEX idx_pn_status_created_at
    ON pending_notifications (status, created_at);

CREATE INDEX idx_pn_grouping
    ON pending_notifications (target_entity_id, event_type, created_at);

CREATE INDEX idx_pn_receiver_entity_event
    ON pending_notifications (receiver_id, target_entity_id, event_type);

CREATE TABLE last_sent_notifications
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receiver_id      BIGINT      NOT NULL,
    target_entity_id BIGINT      NOT NULL,
    event_type       VARCHAR(50) NOT NULL,
    last_sent_at     TIMESTAMPTZ NOT NULL,
    UNIQUE (receiver_id, target_entity_id, event_type)
);