CREATE TABLE telegram_profiles
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id  BIGINT                                  NOT NULL,
    nickname VARCHAR(255)                            NOT NULL,
    chat_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_telegram_profiles PRIMARY KEY (id)
);